import { combineReducers } from "redux";
import {
    authSlices,
    createUserSlices,
    loginSlices,
    createComicSlices,
    createChapterSlices,
    createComic_categoriesSlice,
    createFollowSlices,
    deleteComicSlice,
    deleteUserSlice,
    updateViewsSlice,
    updateUserSlice,
    updateComicSlice,
    allCommentsSlice,
    categorySlice,
    comicSlice,
    allComicSlice,
    paginationSlice,
    comicByIdSlice,
    chapterByIdSlice,
    comicByCategorySlice,
    categoriesByComicSlice,
    chapterOnlyByIdSlice,
    userInfoSlice,
    totalUserSlice,
    totalComicSlice,
    totalChapterSlice,
    comicFollowedSlice,
    allUserSlice,
    followByComicSlice,
    searchSlice,
    checkUserFollowSlice,
} from "./slices/index.js";
const rootReducer = combineReducers({
    categoryApi: categorySlice,
    comicApi: comicSlice,
    createComic: createComicSlices,
    createChapter: createChapterSlices,
    allComic: allComicSlice,
    pagination: paginationSlice,
    comicById: comicByIdSlice,
    chapterById: chapterByIdSlice,
    comic_categories: createComic_categoriesSlice,
    comicByCategory: comicByCategorySlice,
    categoriesByComic: categoriesByComicSlice,
    views: updateViewsSlice,
    chapterOnly: chapterOnlyByIdSlice,
    user: createUserSlices,
    login: loginSlices,
    auth: authSlices,
    userInfo: userInfoSlice,
    totalUser: totalUserSlice,
    totalComic: totalComicSlice,
    totalChapter: totalChapterSlice,
    FollowData: createFollowSlices,
    comicFollowed: comicFollowedSlice,
    allUser: allUserSlice,
    deleteComic: deleteComicSlice,
    deleteUser: deleteUserSlice,
    updateUser: updateUserSlice,
    updateComic: updateComicSlice,
    followByComic: followByComicSlice,
    searchData: searchSlice,
    allComments: allCommentsSlice,
    checkUserFollow: checkUserFollowSlice,
    // Thêm reducers khác của bạn tại đây
});

export default rootReducer;
